### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by DeepuAKD** [AGENT404TRD/BOXVIDRA-EMULATOR#1]
![Screenshot_2024-04-27-13-46-52-85_84d3000e3f4017145260f7618db1d683.jpg](https://github.com/AGENT404TRD/BOXVIDRA-EMULATOR-BETA-/assets/128178674/fdd1fc7c-e762-44a8-adfd-faf8ef7988c7)

**Comment by Ddc6cccccccccccccffffffyuj** [comment]
![Screenshot_20240704_175947_Termux](https://github.com/AGENT404TRD/BOXVIDRA-EMULATOR/assets/170058417/4a3b9245-6e1c-4e71-9054-37bec8bf4da7)
