### ISSUE TITLE
Boxvidra not opening problem

### ISSUE THREAD

**Issue by MrPhryaNikFrosty** [AGENT404TRD/BOXVIDRA-EMULATOR#17]
Boxvidra are not opening at all in my device. I have try to reinstall the termux but still same. Here are the crash log of boxvidra. Hope you will fixed this asap
[mobox_log.txt_wineboot.txt](https://github.com/AGENT404TRD/BOXVIDRA-EMULATOR-BETA-/files/15161351/mobox_log.txt_wineboot.txt)
![Screenshot_20240430_173814](https://github.com/AGENT404TRD/BOXVIDRA-EMULATOR-BETA-/assets/160590916/ef7e85a8-a521-487c-888a-7532fec8fc87)

**Comment by Ddc6cccccccccccccffffffyuj** [comment]
![Uploading Screenshot_20240704_175947_Termux.jpg…]()
