### ISSUE TITLE
She completely deleted the user data of my phone and left nothing behind, I have a complaint against you

### ISSUE THREAD

**Issue by alpozpc** [AGENT404TRD/BOXVIDRA-EMULATOR#20]
She completely deleted the user data of my phone and left nothing behind, I have a complaint against you

**Comment by Tino99999** [comment]
Is this malware? BOXVIDRA has deleted all my files from my phone's internal memory! all files have been deleted

**Comment by MihaiRO1234** [comment]
This repository need to be reported..its not normal...

**Comment by ahmedbarakat2007** [comment]
Boxvidra is hacked by Xoureldeen (winux dev and vectras vm dev)

**Comment by ahmedbarakat2007** [comment]
Don't use it till the original dev fix everything

**Comment by Pcbackups** [comment]
Don't open boxvidra for now.
