### ISSUE TITLE
Wine explore not opening

### ISSUE THREAD

**Issue by knowledgesk** [AGENT404TRD/BOXVIDRA-EMULATOR#23]
Huawei p30 lite 6Gg ram
Wine explore not opening

**Comment by Maks123789** [comment]
Double click Wine Explorer and dont move ur cursor away. I had this problem too

**Comment by Ddc6cccccccccccccffffffyuj** [comment]
في تحديث الامان الاخير في samsung لا يفتح

**Comment by Ddc6cccccccccccccffffffyuj** [comment]
![Screenshot_20240704_175947_Termux](https://github.com/AGENT404TRD/BOXVIDRA-EMULATOR/assets/170058417/7d28ae53-1ebb-4d76-8944-9d61f2d99911)
