### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by MegaGaming2** [AGENT404TRD/BOXVIDRA-EMULATOR#7]
![Screenshot_2024-04-28-08-33-21-62_84d3000e3f4017145260f7618db1d683](https://github.com/AGENT404TRD/BOXVIDRA-EMULATOR-BETA-/assets/97959552/d5cd7f02-b00f-43e4-b489-d6fe142383dc)

**Comment by Rehmaniii** [comment]
Same isshu

**Comment by MegaGaming2** [comment]
Btw don't try it, it's a virus
